energy_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', '127.0.0.1') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER', 'energy_user') }}"
      password: "{{ env_var('PGPASSWORD', '') }}"
      dbname: "{{ env_var('PGDATABASE', 'energy') }}"
      schema: staging        # default/target schema; models override via +schema
      threads: 4
